name: Github Deploy
on: [push]
jobs:
  Deploy-to-Github-Pages:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build Vite Project
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
